<a href="https://colab.research.google.com/github/suumino/tensor/blob/main/final_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

digits = datasets.load_digits()

In [2]:
features = digits.data
target = digits.target
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [3]:
################# make_regression ################
from sklearn.datasets import make_regression

features, target, coefficients = make_regression(n_samples = 100, 
                                                 n_features = 3, 
                                                 n_informative = 3, 
                                                 n_targets = 1, 
                                                 noise = 0.0, 
                                                 coef = True, 
                                                 random_state = 1)
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]


In [4]:
################# make_classification ################
from sklearn.datasets import make_classification

features, target=make_classification(n_samples = 100, 
                                     n_features = 3, 
                                     n_informative = 3, 
                                     n_redundant = 0, 
                                     n_classes = 2, 
                                     weights = [.25, .75], 
                                     random_state = 1)
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]
Target Vector
 [1 0 0]


In [5]:
################### make_blobs ################
from sklearn.datasets import make_blobs

features, target = make_blobs(n_samples = 100, 
                              n_features = 2, 
                              centers = 3, 
                              cluster_std = 0.5, 
                              shuffle = True, 
                              random_state = 1)
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ -1.22685609   3.25572052]
 [ -9.57463218  -4.38310652]
 [-10.71976941  -4.20558148]]
Target Vector
 [0 1 1]


In [6]:
# comma separated values
import pandas as pd

url = 'sample.csv'
dataframe = pd.read_csv(url)
dataframe.head()

street        city    zip  ...  price   latitude   longitude
0      3526 HIGH ST  SACRAMENTO  95838  ...  59222  38.631913 -121.434879
1       51 OMAHA CT  SACRAMENTO  95823  ...  68212  38.478902 -121.431028
2    2796 BRANCH ST  SACRAMENTO  95815  ...  68880  38.618305 -121.443839
3  2805 JANETTE WAY  SACRAMENTO  95815  ...  69307  38.616835 -121.439146
4   6001 MCMAHON DR  SACRAMENTO  95824  ...  81900  38.519470 -121.435768

[5 rows x 12 columns]

In [7]:
import pandas as pd

dataframe = pd.DataFrame()

dataframe['Name'] = ['Jacky Jackson', 'Steven Stevenson']
dataframe['Age'] = [38, 25]
dataframe['Driver'] = [True, False]

dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [8]:
new_person = pd.Series(['Molly Mooney', 40, True], index=['Name', 'Age', 'Driver'])
dataframe.append(new_person, ignore_index=True)

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True

In [9]:
dataframe.shape

(2, 3)

In [10]:
dataframe.describe()

Age
count   2.000000
mean   31.500000
std     9.192388
min    25.000000
25%    28.250000
50%    31.500000
75%    34.750000
max    38.000000

In [11]:
dataframe.iloc[0]

Name      Jacky Jackson
Age                  38
Driver             True
Name: 0, dtype: object

In [12]:
dataframe.iloc[:1]

Name  Age  Driver
0  Jacky Jackson   38    True

In [13]:
import pandas as pd

titanic = 'train.csv'
dataframe = pd.read_csv(titanic)
dataframe.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [14]:
dataframe[dataframe['Sex'] == 'female'].head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[2 rows x 12 columns]

In [15]:
dataframe[(dataframe['Sex'] == 'female') & (dataframe['Age'] >= 60)]

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
275          276         1       1  ...  77.9583    D7         S
366          367         1       1  ...  75.2500   D37         C
483          484         1       3  ...   9.5875   NaN         S
829          830         1       1  ...  80.0000   B28       NaN

[4 rows x 12 columns]

In [16]:
dataframe['Sex'].replace('female', 'Woman').head(2)

0     male
1    Woman
Name: Sex, dtype: object

In [17]:
dataframe['Sex'].replace(['female', 'male'], ['Woman', 'Man']).head(5)

0      Man
1    Woman
2    Woman
3    Woman
4      Man
Name: Sex, dtype: object

In [18]:
dataframe.replace(1, 'One').head(2)

PassengerId Survived Pclass  ...     Fare Cabin Embarked
0         One        0      3  ...   7.2500   NaN        S
1           2      One    One  ...  71.2833   C85        C

[2 rows x 12 columns]

In [19]:
dataframe.head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [20]:
dataframe.rename(columns={'Pclass' : 'Passenger Class'}).head(2)

PassengerId  Survived  Passenger Class  ...     Fare Cabin  Embarked
0            1         0                3  ...   7.2500   NaN         S
1            2         1                1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [21]:
dataframe.rename(columns={'Pclass': 'Passenger Class', 'Sex': 'Gender'}).head(2)

PassengerId  Survived  Passenger Class  ...     Fare Cabin  Embarked
0            1         0                3  ...   7.2500   NaN         S
1            2         1                1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [22]:
import collections

column_names = collections.defaultdict(str)
for name in dataframe.columns:
  column_names[name]

column_names

defaultdict(str,
            {'Age': '',
             'Cabin': '',
             'Embarked': '',
             'Fare': '',
             'Name': '',
             'Parch': '',
             'PassengerId': '',
             'Pclass': '',
             'Sex': '',
             'SibSp': '',
             'Survived': '',
             'Ticket': ''})

In [23]:
print('Maximum:', dataframe['Age'].max())
print('Minimum:', dataframe['Age'].min())
print('Mean:', dataframe['Age'].mean())
print('Sum:', dataframe['Age'].sum())
print('Count:', dataframe['Age'].count())

Maximum: 80.0
Minimum: 0.42
Mean: 29.69911764705882
Sum: 21205.17
Count: 714


In [24]:
#### var: 분산, std: 표준편차, kurt: 첨도, skew: 비대칭도, sem: 표준오차, mode: 최빈값, median: 중간값 ####

In [25]:
dataframe.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [26]:
dataframe['Sex'].unique()

array(['male', 'female'], dtype=object)

In [27]:
dataframe['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [28]:
dataframe['Sex'].nunique()

2

In [29]:
dataframe[dataframe['Age'].isnull()]

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
5              6         0       3  ...   8.4583   NaN         Q
17            18         1       2  ...  13.0000   NaN         S
19            20         1       3  ...   7.2250   NaN         C
26            27         0       3  ...   7.2250   NaN         C
28            29         1       3  ...   7.8792   NaN         Q
..           ...       ...     ...  ...      ...   ...       ...
859          860         0       3  ...   7.2292   NaN         C
863          864         0       3  ...  69.5500   NaN         S
868          869         0       3  ...   9.5000   NaN         S
878          879         0       3  ...   7.8958   NaN         S
888          889         0       3  ...  23.4500   NaN         S

[177 rows x 12 columns]

In [30]:
dataframe[dataframe['Age'].isnull()].head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
5             6         0       3  ...   8.4583   NaN         Q
17           18         1       2  ...  13.0000   NaN         S

[2 rows x 12 columns]

In [31]:
dataframe.drop('Age', axis=1).head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 11 columns]

In [32]:
dataframe.drop(['Age', 'Sex'], axis=1).head(2)

PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked
0            1         0       3  ...   7.2500    NaN         S
1            2         1       1  ...  71.2833    C85         C

[2 rows x 10 columns]

In [33]:
dataframe[dataframe['Sex'] != 'male'].head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[2 rows x 12 columns]

In [35]:
dataframe[dataframe['Name'] != "Braund, Mr. Owen Harris"].head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[2 rows x 12 columns]

In [39]:
print('Number', len(dataframe))
print('Number', len(dataframe.drop_duplicates()))

Number 891
Number 891


In [41]:
dataframe.drop_duplicates(subset=['Sex'])

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [42]:
dataframe.drop_duplicates(subset=['Sex'], keep='last')

PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
888          889         0       3  ...  23.45   NaN         S
890          891         0       3  ...   7.75   NaN         Q

[2 rows x 12 columns]

In [43]:
dataframe.drop_duplicates(subset=['Pclass'])

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
9           10         1       2  ...  30.0708   NaN         C

[3 rows x 12 columns]

In [44]:
dataframe.groupby('Sex').mean()

PassengerId  Survived    Pclass  ...     SibSp     Parch       Fare
Sex                                      ...                               
female   431.028662  0.742038  2.159236  ...  0.694268  0.649682  44.479818
male     454.147314  0.188908  2.389948  ...  0.429809  0.235702  25.523893

[2 rows x 7 columns]

In [46]:
dataframe.groupby('Survived')['Name'].count()

Survived
0    549
1    342
Name: Name, dtype: int64

In [47]:
dataframe.groupby(['Sex', 'Survived'])['Age'].mean()

Sex     Survived
female  0           25.046875
        1           28.847716
male    0           31.618056
        1           27.276022
Name: Age, dtype: float64

In [52]:
import pandas as pd
import numpy as np

time_index = pd.date_range('06/06/2017', periods=100000, freq='30S')
dataframe = pd.DataFrame(index=time_index)
dataframe['Sale_Amount'] = np.random.randint(1, 10, 100000)
dataframe.resample("W").sum()

Sale_Amount
2017-06-11        86970
2017-06-18       100927
2017-06-25       101477
2017-07-02       100817
2017-07-09        99933
2017-07-16        10516

In [53]:
dataframe.resample('2W').mean()

Sale_Amount
2017-06-11     5.032986
2017-06-25     5.019940
2017-07-09     4.978919
2017-07-23     5.055769

In [54]:
dataframe.resample('M').count()

Sale_Amount
2017-06-30        72000
2017-07-31        28000

In [76]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], 
                    [-100.1], 
                    [0], 
                    [100.1],
                    [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [77]:
x = np.array([[-1000.1], 
              [-200.2], 
              [500.5], 
              [600.6],
              [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [78]:
print("Mean:", round(standardized.mean()))
print("Standard deviation:", standardized.std())

Mean: 0
Standard deviation: 1.0


In [80]:
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(x)    # 0 / 25 / 50 / 75 / 100

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

In [81]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples = 10, 
                         n_features = 2, 
                         centers = 1, 
                         random_state = 1)
features[0, 0] = 10000
features[0, 1] = 10000
outlier_detector = EllipticEnvelope(contamination=.1)
outlier_detector.fit(features)
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])